---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: navcon
  name: navcon
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: navcon
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: navcon
spec:
  selector:
    matchLabels:
      app: navcon
  replicas: 3
  template:
    metadata:
      labels:
        app: navcon
    spec:
      containers:
      - name: navcon
        image: bstick12/navcon-docker:latest
        ports:
        - containerPort: 8080
